[build]
  base = "invitacion-3-anios"
  command = "npm run build"
  publish = "dist/invitacion-3-anios/browser"

[functions]
  directory = "invitacion-3-anios/netlify/functions"
  node_bundler = "esbuild"